[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
[[redirects]]
  from = "/api/uploadFactura"
  to = "/.netlify/functions/uploadFactura"
  status = 200